# Lica Robert Mihai <robertlica21@gmail.com>

CC=g++ -std=c++11
CFLAGS=-Wall -Wextra

P1_N=bani.cpp
P2_N=gard.cpp
P3_N=bomboane.cpp
P4_N=sala.cpp

P1=bani
P2=gard
P3=bomboane
P4=sala

build:
	$(CC) $(CFLAGS) $(P1_N) -o $(P1)
	$(CC) $(CFLAGS) $(P2_N) -o $(P2)
	$(CC) $(CFLAGS) $(P3_N) -o $(P3)
	$(CC) $(CFLAGS) $(P4_N) -o $(P4)
	
run-p1:      # nume necesar
	./$(P1)
run-p2:      # nume necesar
	./$(P2)
run-p3:      # nume necesar 
	./$(P3)
run-p4:      # nume necesar 
	./$(P4)
clean:		 # nume necesar
	rm $(P1) $(P2) $(P3) $(P4)
