build:
	g++ -std=c++11 -Wall -Wextra p1.cpp -o p1
	g++ -std=c++11 -Wall -Wextra p2.cpp -o p2
	g++ -std=c++11 -Wall -Wextra p3.cpp -o p3
	# g++ -std=c++11 -Wall -Wextra bonus.cpp -o p4

run-p1:
	./p1
run-p2:
	./p2
run-p3:
	./p3
#run-p4:
#	./p4

clean:
	rm -f p1 p2 p3 p4
